[versions]
mindustry = "159"
xcore-protocol = "0.5.0-SNAPSHOT"

# Plugins
toxopid = "4.2.0"
shadow = "9.3.0"

# Dependencies
cloud-mindustry = "0.2.0-SNAPSHOT"
mongodb = "5.9.1"
gson = "2.12.1"
jbcrypt = "0.4"
netty = "4.1.135.Final"
lettuce = "6.8.2.RELEASE"
jackson = "2.22.1"
avaje = "12.5"
flubundle = "1.3"
lombok = "1.18.44"
junit = "5.14.0"
mockito = "5.23.0"
assertj = "3.27.7"
testcontainers = "1.21.4"

[plugins]
toxopid = { id = "com.xpdustry.toxopid", version.ref = "toxopid" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
cloud-mindustry = { module = "org.xcore:cloud-mindustry", version.ref = "cloud-mindustry" }
xcore-protocol-java = { module = "org.xcore:xcore-protocol-java", version.ref = "xcore-protocol" }
mongodb-sync = { module = "org.mongodb:mongodb-driver-sync", version.ref = "mongodb" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jbcrypt = { module = "org.mindrot:jbcrypt", version.ref = "jbcrypt" }
netty-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }
lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
jackson-dataformat-toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }
avaje-inject = { module = "io.avaje:avaje-inject", version.ref = "avaje" }
avaje-inject-generator = { module = "io.avaje:avaje-inject-generator", version.ref = "avaje" }
avaje-inject-test = { module = "io.avaje:avaje-inject-test", version.ref = "avaje" }
flubundle = { module = "com.ospx:flubundle", version.ref = "flubundle" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
testcontainers-junit-jupiter = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
