name: Java CI

on: [ push, workflow_dispatch ]

jobs:
  buildJar:
    permissions: write-all
    runs-on: self-hosted
    env:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-arm64
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x gradlew
      - name: Build plugin jar
        run: ./gradlew jar
      - name: Save to build branch
        uses: planetoftheweb/copy-to-branches@v1
        env:
          key: main
          files: /build/libs/XCore-plugin-*.jar
          branches: build
