name: Build

on: [ push, workflow_dispatch ]

jobs:
  buildJar:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew jar
        
      - name: Upload artifacts
        run: cp build/libs/XCore-plugin-*.jar ../../../build/
